quotes = [
	"I Do Anything And Everything Mr. Stark Requires. Including Occasionally Taking Out The Trash", 
	"I Prefer The Weapon You Only Have To Fire Once",
	"I Am Iron Man",
	"Sometimes you gotta run before you can walk",
	"Hulk Smash!",
	"Sir! I'm gonna have to ask you to exit the donut",
	"If you could make God bleed, people would cease to believe in him, there will be blood in the water, the sharks will come. All I have to do is sit back and watch as the world consumes you",
	"What is, and always will be my greatest creation, is you",
	"I built this for you. It represents my life's work. This is the key to the future. I'm limited by the technology of my time, but one day you'll figure this out. And when you do, you will change the world",
	"Whosoever holds this hammer, if he be worthy shall posses the power of thor.",
	"You are no match for the mighty Thor!!",
	"I have no plans to die today",
	"You're big. I've fought bigger.",
	"Hail Hydra!",
	"The Little Guy From Brooklyn Who Was Too Dumb Not To Run Away From A Fight. I'm Following Him",
	"You could have the power of the gods! Yet you wear a flag on your chest and think you fight a battle of nations! I have seen the future, Captain! There are no flags!",
	"Because the strong man who has known power all his life, may lose respect for that power, but a weak man knows the value of strength, and knows... compassion.",
	"Yeah, it's just...I had a date.",
	"I can do this all day.",
	"I don't like bullies. I don't care where they're from.",
	"Whatever happens , Stay who you are. Not just a soldier ,but a good Man .",
	"We have a Hulk.",
	"That man is playing Galaga! Thought we wouldn't notice, but we did.",
	"The Avengers. It's what we call ourselves. Sorta like a team. Earth's Mightiest Heroes type thing.",
	"There's only one God ma'am, and I'm pretty sure he doesn't dress like that.",
	"He's adopted",
	"Puny God!",
	"You lack conviction.",
	"You know, the last time I was in Germany and saw a man standing above eveyrybody else, we ended up disagreeing.",
	"That's my secret captain I'm always angry",
	"I understand that the council has made a decision, but given that it's a stupid-ass decision, I've chosen to ignore it!",
	"What the hell- What just happened? Please tell me nobody kissed me.",
	"There was an idea... to bring together a group of remarkable people. To make them work together when we needed them to, to fight the battles that... we never could. Phil Coulson died still believing in that idea. In heroes.",
	"If we can't protect the earth, you can be damned sure we'll avenge it.",
	"Tell him to suit up I'm bringing the party to you.",
	"You're a laboratory experiment, Rogers. Everything special about you came out of a bottle!",
	"I've got red in my ledger. I'd like to wipe it out.",
	"Alright. Hey. Alright. Good job, guys. Let's just not come in tomorrow. Let's just take a day. Have you ever tried shawarma? There's a shawarma joint about two blocks from here. I don't know what it is, but I wanna try it.",
	"Superheroes? In New York? Gimme a break!",
	"I got that reference!",
	"I am Loki of Asgard and I am burdened with glorious purpose.",
	"Doth thou mother know you weareth her drapes?",
	"Genius, billionaire, playboy, philanthropist.",
	"Lets do a head count. A couple of master assassins, a demigod, a super soldier... and you've managed to piss off every single one of them.",
	"My name is Tony Stark and I'm not afraid of you. I know you're a coward. So I've decided, that you just died pal.",
	"What are you waiting for? It's Christmas. Take 'em to church.",
	"We create our own demons.",
	"There's nothing more reassuring than realizing that the world is crazier than you are.",
	"Attention all S.H.I.E.L.D. agents. This is Steve Rogers. You've heard a lot about me over the last few days. Some of you were even ordered to hunt me down. But I think it's time you know the truth. S.H.I.E.L.D. is not what we thought it was. It has been taken over by HYDRA. Alexander Pierce is their leader. The S.T.R.I.K.E. and Insight crew are HYDRA as well. We don't know how many more, but I know they're in the building. They could be standing right next to you. They almost have what they want: absolute control. They shot Nick Fury, and it won't end there. If you launch those helicarriers today, HYDRA will be able to kill anyone that stands in their way. They must be stopped. I know I'm asking a lot. The price of freedom is high; it always has been. But it's a price I'm willing to pay. And if I'm the only one, then so be it. But I'm willing to bet I'm not.?",
	"Then finish it. Because I'm with you to the end of the line.",
	"On your left.",
	"I am so fired!",
	"I have lived most my life surrounded by my enemies. I would be grateful to die among my friends.",
	"I am Groot.",
	"You said it yourself, bitch. We're the Guardians of the Galaxy.",
	"Oh will you shut up about that? God, 20 years you've been throwing that in my face. Like it's some great thing, not eating me. Normal people don't even think about eating someone else, much less, that person having to be grateful for it.",
	"Ronan was just a puppet. Thanos is the one I really have to kill.",
	"Nothing goes over my head. My reflexes are too fast. I would catch it.",
	"We are Groot.",
	"I'm gonna die, surrounded by the biggest idiots in the galaxy.",
	"Back in the day I had eyes everywhere, and you kids had all the tech you could dream of, but here we all are back on earth, nothing but our wit and our will to save the world, so stand outwit the platinum bastard!",
	"Do you see it? The beauty of it? The inevitability? You rise..only to fall. You Avengers, you are my meteor, my swift and terrible sword and the earth will crack...with the weight of your failure. Purge me from your computers, turn your own flesh against me. It means nothing. When the dust settles, the only thing left living in this world...will be metal.",
	"You step outside that door, you're an Avenger.",
	"What doesn't kill you makes you stronger.",
	"The most versatile substance on the planet, And they used it to build a Frisbee",
	"You get hurt, hurt 'em back. You get killed... walk it off.",
	"I once had strings, but now I'm free... There are no strings on me!",
	"Second chances don't come around all that often. I suggest you take a really close look at it. This is your chance to earn that look in your daughter's eyes, to become the hero that she already thinks you are.",
	"Is this stuff coming out of you?",
	"The Black Panther has been the protector of Wakanda for generations. A mantle passed from warrior to warrior. And now because your friend murdered my father, I also wear the mantle of king. So I ask you, as both warrior and king, how long do you think you can keep your friend safe from me?",
	"Are you Tony Stank?",
	"An empire toppled by its enemies can rise again, but one which crumbles from within? That's dead... forever.",
	"I asked her (Peggy Carter) once how she managed to master diplomacy and espionage in a time when no one wanted to see a woman succeed at either. She said compromise where you can, but where you can't, don't. Even if everyone is telling you that something wrong is something right. Even if the whole world is telling you to move. It is your duty to plant yourself like a tree, to look them in the eye and say, no, you move.",
	"Hank Pym always said Never trust a Stark.",
	"Vengeance has consumed you, it's consumed them... I'm not letting it consume me.",
	"Hey captain big fan, I'm spider man",
	"I'm trying to prevent you from tearing The Avengers apart.",
	"You don't deserve that! My father made that shield!",
	"So, you like cats?",
	"In my culture, death is not the end. It's more of a stepping off point. You reach out with both hands and Bast and Sekhmet, they lead you into the green veld where... you can run forever.",
	"You have a metal arm? That is awesome, dude.",
	"All right, I've run out of patience. Underoos!",
	"I'm sorry Tony.... I wouldn't do this if I had any other choice... But he's my friend.",
	"I know we're not perfect, but the safest hands are still our own.",
	"You're a man looking at the world through a keyhole. You've spent your life trying to widen it. Your work saved the lives of thousands. What if I told you that reality is one of many?",
	"You Cannot Beat A River Into Submission. You Have To Surrender To Its Current And Use Its Power As Your Own.",
	"People Think In Terms Of Good And Evil When Really Time Is The True Enemy Of Us All.",
	"We Don't Get To Choose Our Time.",
	"The Bill Comes Due. Always.",
	"Dormammu, I've Come To Bargain.",
	"He says, welcome to the frickin' Guardians of the Galaxy. Only he didn't use frickin'.",
	"Sometimes, the thing you've been looking for your whole life is right there beside you all along.",
	"Awesome! We're really gonna be able to jack up our prices if we're two-time galaxy savers.",
	"When you're ugly, and someone loves you, you know they love you for who you are... beautiful people never know who to trust.",
	"There are two types of beings in the universe, those who dance, and those who do not.",
	"I'm Mary Poppins, y'all!",
	"What if somebody had died today? Different story, right? Because that’s on you. And if you die, I feel like that’s on me.",
	"Ironman! Hey, what are you doing robbing banks? You’re a billionaire.",
	"If you’re nothing without that suit, then you shouldn’t have it.",
	"I just like coming here to sketch people in crisis.",
	"I choose to run towards my problems, and not away from them. Because's that what heroes do.",
	"Last time we saw you, you were trying to kill everyone. What are you up to these days?",
	"Yes, me too. On many, many occasions. There was one time when we were children, he transformed himself into a snake, and he knows that I love snakes. So, I went to pick up the snake to admire it and he transformed back into himself and he was like, Blergh, it's me!. And he stabbed me. We were eight at the time.",
	"Darling, you have no idea what's possible.",
	"Allow me to introduce myself. My name is Korg. I'm kind of like the leader in here. I'm made of rocks, as you can see, but don't let that intimidate you. You don't need to be afraid, unless you're made of scissors! Just a little Rock, Paper, Scissors joke for you.",
	"Asgard is not a place, it's a people.",
	"Are you Thor, the god of hammers?",
	"You are a good man, with a good heart. And it's hard for a good man to be a king.",
	"You're telling me that the king of a Third World country runs around in a bulletproof cat suit?",
	"In times of crisis, the wise build bridges while the foolish build barriers.",
	"As you can see, I am not dead.",
	"Wakanda Forever!",
	"What's The Matter With You Kids? You Never Seen A Spaceship Before?",
	"Dude, You're Embarrassing Me In Front Of The Wizards.",
	"It's Like A Pirate Had A Baby With An Angel.",
	"Dread It, Run From It, Destiny Arrives All The Same.",
	"I Assure You, Brother. The Sun Will Shine On Us Again.",
	"Get Lost, Squidward.",
	"We're In The Endgame Now.",
	"I’m Not Looking For Forgiveness, And I’m Way Past Asking Permission. Earth Just Lost Her Best Defender, So We're Here To Fight.",
	"Mr. Stark, I Don't Feel So Good.",
	"A small price to pay for salvation.",
	"I know what it's like to lose. To feel so desperately that you're right, yet to fail nonetheless. It's frightening, turns the legs to jelly. I ask you to what end? Dread it. Run from it. Destiny arrives all the same. And now it's here. Or should I say, I am.",
	"There's an Ant-Man and a Spider-Man?",
	"Wong, you're invited to my wedding.",
	"Ok, let me ask you this one time: What master do you serve?",
	"Oh, what master do I serve? What am I supposed to say, Jesus?",
	"You... will never be... a god.",
	"You should have gone for the head.",
	"You throw another moon at me and I'm gonna lose it!",
	"Oh, you're using made-up names. Um... I'm Spider-Man, then.",
	"Evacuate the city! Engage all defenses! And get this man a shield!",
	"You guys are so screwed now!",
	"Holy shit. WE'RE ALL GONNA DIE!",
	"Allfather, let the Dark Magic flow through me one last time...",
	"You have my respect, Stark. When I'm done, half of humanity will still be alive. I hope they remember you.",
	"A soul for a soul.",
	"Broke up? Like a band? Like the Beatles?",
	"... guiding others to a treasure I cannot possess.",
	"Fourteen million six hundred and five.",
	"The hardest choices require the strongest will.",
	"Bring me Thanos!",
	"A simple spell, but quite unbreakable.",
	"Alright kid, you're an Avenger now...",
	"Should we bow?",
	"Yeah, he's a king.",
	"We don't do that here.",
	"Hold on, you gave her wings?",
	"Call me ‘young lady’ again and I’m gonna put my foot in a place it’s not supposed to be.",
	"This isn’t about fighting wars. It’s about ending them.",
	"Species: Human Male. Threat: Low to None.",
	"I lost the kid.",
	"This is the fight of our lives. We're going to win. Whatever it takes.",
	"Hey, man! Make love, not war!",
	"If I tell you what happens, it won’t happen.",
	"You took everything from me.",
	"I don't even know who you are.",
	"I keep telling everybody they should move on and grow. Some do. But not us.",
	"Avengers! Assemble!",
	"Part of the Journey is the End.",
	"Everybody wants a happy ending, right? But it doesn't always roll that way. Maybe this time. I'm hoping if you play this back, it's in celebration.",
	"I love you 3000.",
	"Let’s go get this son of a bitch",
	"I'm still worthy",
	"I am… inevitable",
	"Don't do that. Don't give me hope.",
	"That is America’s ass.",
	"I came for science. I'm leaving 'cause of witches. Welcome to the new dark ages!",
	"Boh!",
	"Don't ever apologize for being the smartest one in the room.",
	"Everywhere I go, I see his face.",
	"You're head of security and your password is password?",
	"Oh, I love Led Zeppelin!",
	"Your power exceeds that of the Sorcerer Supreme! It’s your destiny to destroy the world.",	
	"So you’re saying the universe created a sitcom starring two Avengers?",
	"It was Agatha All Along!",
	"You are familiar with the thought experiment the Ship of Theseus in the field of identity metaphysics?",
	"What is grief, if not love persevering?",
	"The world’s broken. Everyone’s just looking for someone to fix it.",
	"I read The Hobbit in 1937 when it first came out.",
	"A sorcerer is a wizard without a hat.",
	" I am Loki of Asgard. And I am burdened with glorious purpose.",
	"Existence is chaos. Nothing makes any sense, so we try to make some sense of it.",
	"Love is a dagger. It's a weapon to be wielded far away, or up close. You can see yourself in it. It's beautiful. Until it makes you bleed. But ultimately, when you reach for it, it isn't real.",
	"Pain only makes us stronger.",
	" Never let them take your heart.",
	"Time, space, reality. It’s more than a linear path. It’s a prism of endless possibility. Where a single choice can branch out into infinite realities creating alternate worlds from the ones you know. I am The Watcher. I am your guide through these vast new realities. Follow me and ponder the question, What If…?",
	"I observe all that transpires here, but I do not, cannot, will not interfere.",
	"But my Aunt May says…used to say, that if we don’t keep smiling when they can’t, then we might as well just be gone too.",
	"Wingardium leviosa!",
	"You Can't Outrun Who You Really Are.",
	"If You Aim At Nothing, You Hit Nothing.",
	"This planet and this people have changed me.",
	"When you love something, you protect it.",
	"Without their flaws, they wouldn’t be human.",
	"You know, some people have actually called me the world’s greatest archer.",
	"Sometimes the paths we're on, they wind around in ways that we never would have expected. All you can do is keep moving forward. Even on days when honestly, it all just kind of feels like shit.",
	"If you expect disappointment, then you can never really get disappointed.",
	"With great power, there must also come great responsibility.",
	" I’m a really good lawyer.",
	" That feels weird, but I’ll allow it.",
	"Hello, Peter.",
	"Scooby Doo This Shit.",
	"They're starting to come through, and I can't stop them!",
	"You know, I'm something of a scientist myself.",
	"Trying to do better.",
	"The Avengers... is that a band?"
]

module.exports = {quotes};